# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfu_init.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dfu_init.proto',
  package='dfu',
  serialized_pb=_b('\n\x0e\x64\x66u_init.proto\x12\x03\x64\x66u\";\n\x06hash_t\x12#\n\thash_type\x18\x01 \x02(\x0e\x32\x10.dfu.hash_type_t\x12\x0c\n\x04hash\x18\x02 \x02(\x0c\"\x84\x01\n\tcommand_t\x12\x1f\n\x07op_code\x18\x01 \x01(\x0e\x32\x0e.dfu.op_code_t\x12)\n\x0cinit_command\x18\x02 \x01(\x0b\x32\x13.dfu.init_command_t\x12+\n\rreset_command\x18\x03 \x01(\x0b\x32\x14.dfu.reset_command_t\"\xde\x01\n\x0einit_command_t\x12\x1e\n\nfw_version\x18\x01 \x01(\r:\n4294967295\x12\x1e\n\nhw_version\x18\x02 \x01(\r:\n4294967295\x12\x12\n\x06sd_req\x18\x03 \x03(\rB\x02\x10\x01\x12)\n\x04type\x18\x04 \x01(\x0e\x32\x0e.dfu.fw_type_t:\x0b\x41PPLICATION\x12\x0f\n\x07sd_size\x18\x05 \x01(\r\x12\x0f\n\x07\x62l_size\x18\x06 \x01(\r\x12\x10\n\x08\x61pp_size\x18\x07 \x01(\r\x12\x19\n\x04hash\x18\x08 \x01(\x0b\x32\x0b.dfu.hash_t\"\"\n\x0freset_command_t\x12\x0f\n\x07timeout\x18\x01 \x02(\r\"\xbe\x01\n\x10signed_command_t\x12\x1f\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x0e.dfu.command_t\x12>\n\x0esignature_type\x18\x02 \x02(\x0e\x32&.dfu.signed_command_t.signature_type_t\x12\x11\n\tsignature\x18\x03 \x02(\x0c\"6\n\x10signature_type_t\x12\x15\n\x11\x45\x43\x44SA_P256_SHA256\x10\x00\x12\x0b\n\x07\x45\x44\x32\x35\x35\x31\x39\x10\x01* \n\top_code_t\x12\t\n\x05RESET\x10\x00\x12\x08\n\x04INIT\x10\x01*W\n\tfw_type_t\x12\x0e\n\nSOFTDEVICE\x10\x01\x12\x0e\n\nBOOTLOADER\x10\x02\x12\x19\n\x15SOFTDEVICE_BOOTLOADER\x10\x03\x12\x0f\n\x0b\x41PPLICATION\x10\x04*G\n\x0bhash_type_t\x12\x0b\n\x07NO_HASH\x10\x00\x12\x07\n\x03\x43RC\x10\x01\x12\n\n\x06SHA128\x10\x02\x12\n\n\x06SHA256\x10\x03\x12\n\n\x06SHA512\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OP_CODE_T = _descriptor.EnumDescriptor(
  name='op_code_t',
  full_name='dfu.op_code_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INIT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=673,
  serialized_end=705,
)
_sym_db.RegisterEnumDescriptor(_OP_CODE_T)

op_code_t = enum_type_wrapper.EnumTypeWrapper(_OP_CODE_T)
_FW_TYPE_T = _descriptor.EnumDescriptor(
  name='fw_type_t',
  full_name='dfu.fw_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOFTDEVICE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOTLOADER', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTDEVICE_BOOTLOADER', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLICATION', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=707,
  serialized_end=794,
)
_sym_db.RegisterEnumDescriptor(_FW_TYPE_T)

fw_type_t = enum_type_wrapper.EnumTypeWrapper(_FW_TYPE_T)
_HASH_TYPE_T = _descriptor.EnumDescriptor(
  name='hash_type_t',
  full_name='dfu.hash_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_HASH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA128', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA256', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA512', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=796,
  serialized_end=867,
)
_sym_db.RegisterEnumDescriptor(_HASH_TYPE_T)

hash_type_t = enum_type_wrapper.EnumTypeWrapper(_HASH_TYPE_T)
RESET = 0
INIT = 1
SOFTDEVICE = 1
BOOTLOADER = 2
SOFTDEVICE_BOOTLOADER = 3
APPLICATION = 4
NO_HASH = 0
CRC = 1
SHA128 = 2
SHA256 = 3
SHA512 = 4


_SIGNED_COMMAND_T_SIGNATURE_TYPE_T = _descriptor.EnumDescriptor(
  name='signature_type_t',
  full_name='dfu.signed_command_t.signature_type_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ECDSA_P256_SHA256', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ED25519', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=617,
  serialized_end=671,
)
_sym_db.RegisterEnumDescriptor(_SIGNED_COMMAND_T_SIGNATURE_TYPE_T)


_HASH_T = _descriptor.Descriptor(
  name='hash_t',
  full_name='dfu.hash_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_type', full_name='dfu.hash_t.hash_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='dfu.hash_t.hash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=82,
)


_COMMAND_T = _descriptor.Descriptor(
  name='command_t',
  full_name='dfu.command_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_code', full_name='dfu.command_t.op_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_command', full_name='dfu.command_t.init_command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reset_command', full_name='dfu.command_t.reset_command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=217,
)


_INIT_COMMAND_T = _descriptor.Descriptor(
  name='init_command_t',
  full_name='dfu.init_command_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fw_version', full_name='dfu.init_command_t.fw_version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=4294967295,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hw_version', full_name='dfu.init_command_t.hw_version', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=4294967295,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sd_req', full_name='dfu.init_command_t.sd_req', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='type', full_name='dfu.init_command_t.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sd_size', full_name='dfu.init_command_t.sd_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bl_size', full_name='dfu.init_command_t.bl_size', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_size', full_name='dfu.init_command_t.app_size', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='dfu.init_command_t.hash', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=442,
)


_RESET_COMMAND_T = _descriptor.Descriptor(
  name='reset_command_t',
  full_name='dfu.reset_command_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout', full_name='dfu.reset_command_t.timeout', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=478,
)


_SIGNED_COMMAND_T = _descriptor.Descriptor(
  name='signed_command_t',
  full_name='dfu.signed_command_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='dfu.signed_command_t.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature_type', full_name='dfu.signed_command_t.signature_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='dfu.signed_command_t.signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNED_COMMAND_T_SIGNATURE_TYPE_T,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=671,
)

_HASH_T.fields_by_name['hash_type'].enum_type = _HASH_TYPE_T
_COMMAND_T.fields_by_name['op_code'].enum_type = _OP_CODE_T
_COMMAND_T.fields_by_name['init_command'].message_type = _INIT_COMMAND_T
_COMMAND_T.fields_by_name['reset_command'].message_type = _RESET_COMMAND_T
_INIT_COMMAND_T.fields_by_name['type'].enum_type = _FW_TYPE_T
_INIT_COMMAND_T.fields_by_name['hash'].message_type = _HASH_T
_SIGNED_COMMAND_T.fields_by_name['command'].message_type = _COMMAND_T
_SIGNED_COMMAND_T.fields_by_name['signature_type'].enum_type = _SIGNED_COMMAND_T_SIGNATURE_TYPE_T
_SIGNED_COMMAND_T_SIGNATURE_TYPE_T.containing_type = _SIGNED_COMMAND_T
DESCRIPTOR.message_types_by_name['hash_t'] = _HASH_T
DESCRIPTOR.message_types_by_name['command_t'] = _COMMAND_T
DESCRIPTOR.message_types_by_name['init_command_t'] = _INIT_COMMAND_T
DESCRIPTOR.message_types_by_name['reset_command_t'] = _RESET_COMMAND_T
DESCRIPTOR.message_types_by_name['signed_command_t'] = _SIGNED_COMMAND_T
DESCRIPTOR.enum_types_by_name['op_code_t'] = _OP_CODE_T
DESCRIPTOR.enum_types_by_name['fw_type_t'] = _FW_TYPE_T
DESCRIPTOR.enum_types_by_name['hash_type_t'] = _HASH_TYPE_T

hash_t = _reflection.GeneratedProtocolMessageType('hash_t', (_message.Message,), dict(
  DESCRIPTOR = _HASH_T,
  __module__ = 'dfu_init_pb2'
  # @@protoc_insertion_point(class_scope:dfu.hash_t)
  ))
_sym_db.RegisterMessage(hash_t)

command_t = _reflection.GeneratedProtocolMessageType('command_t', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND_T,
  __module__ = 'dfu_init_pb2'
  # @@protoc_insertion_point(class_scope:dfu.command_t)
  ))
_sym_db.RegisterMessage(command_t)

init_command_t = _reflection.GeneratedProtocolMessageType('init_command_t', (_message.Message,), dict(
  DESCRIPTOR = _INIT_COMMAND_T,
  __module__ = 'dfu_init_pb2'
  # @@protoc_insertion_point(class_scope:dfu.init_command_t)
  ))
_sym_db.RegisterMessage(init_command_t)

reset_command_t = _reflection.GeneratedProtocolMessageType('reset_command_t', (_message.Message,), dict(
  DESCRIPTOR = _RESET_COMMAND_T,
  __module__ = 'dfu_init_pb2'
  # @@protoc_insertion_point(class_scope:dfu.reset_command_t)
  ))
_sym_db.RegisterMessage(reset_command_t)

signed_command_t = _reflection.GeneratedProtocolMessageType('signed_command_t', (_message.Message,), dict(
  DESCRIPTOR = _SIGNED_COMMAND_T,
  __module__ = 'dfu_init_pb2'
  # @@protoc_insertion_point(class_scope:dfu.signed_command_t)
  ))
_sym_db.RegisterMessage(signed_command_t)


_INIT_COMMAND_T.fields_by_name['sd_req'].has_options = True
_INIT_COMMAND_T.fields_by_name['sd_req']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
